### ISSUE TITLE
Just a little tip

### ISSUE THREAD

**Issue by regnerisch** [radenadri/cat-votes#2]
https://github.com/radenadri/cat-votes/blob/f7be2563327d9915d73f173d9f8ad7ac0234070f/src/App/Admin/Cats/Controllers/BreedController.php#L47

```php
    public function store(BreedRequest $request, CreateBreedAction $action) : RedirectResponse
    {
        $data = BreedData::fromRequest($request);

        $action->execute($data);

        return Redirect::route('breed.index')->with('message', 'Breed saved!');
    }
```

You should use Laravels DI to inject your action. Pass the DTO ($data) to the `execute` method and use `__construct()` to profit once again from DI. For example: 

```php
class CreateUserAction
{
  public function __construct(protected SendUserUpdatedMailAction $sendUserUpdatedMailAction) {}

  public function execute(User $user, UserData $data)
  {
    $user->update($data->toArray());

    $this->sendUserUpdatedMailAction->execute($user);

    return $user;
  }
}
```

**Comment by radenadri** [comment]
> https://github.com/radenadri/cat-votes/blob/f7be2563327d9915d73f173d9f8ad7ac0234070f/src/App/Admin/Cats/Controllers/BreedController.php#L47
> 
> ```
>     public function store(BreedRequest $request, CreateBreedAction $action) : RedirectResponse
>     {
>         $data = BreedData::fromRequest($request);
> 
>         $action->execute($data);
> 
>         return Redirect::route('breed.index')->with('message', 'Breed saved!');
>     }
> ```
> 
> You should use Laravels DI to inject your action. Pass the DTO ($data) to the `execute` method and use `__construct()` to profit once again from DI. For example:
> 
> ```
> class CreateUserAction
> {
>   public function __construct(protected SendUserUpdatedMailAction $sendUserUpdatedMailAction) {}
> 
>   public function execute(User $user, UserData $data)
>   {
>     $user->update($data->toArray());
> 
>     $this->sendUserUpdatedMailAction->execute($user);
> 
>     return $user;
>   }
> }
> ```

Alright thanks for the tip! I never thought of it 😅. Gonna have to refactor
